#!/bin/bash

current_dir=$(pwd)

if [[ ! $(dirname $(dirname "$current_dir" )) =~ "plugins" ]]; then
    echo -e "\nNot in the plugin root directory\n"
    exit 1
fi

echo -e "\ntest && commit -a || restore .\n"

app_dir=$(dirname $(dirname $(dirname $current_dir)))
phpunit=$app_dir/lib/pkp/lib/vendor/phpunit/phpunit/phpunit
test_config=$app_dir/lib/pkp/tests/phpunit-env2.xml

run_phpunit() {
    output=$(php $phpunit --configuration $test_config -v "$1")
    echo "$output"
    if (echo "$output" | grep -q "FAILURES!") || (echo "$output" | grep -q "ERRORS!"); then
        return 1
    else
        return 0
    fi
}

find . -name tests -type d | while read -r dir; do
    run_phpunit "$dir"
done

[ $? -eq 1 ] && git restore . || git commit -a

echo -e "\nEND OF TCR"
