#!/bin/bash

current_dir=$(pwd)

if [[ ! $(dirname $(dirname "$current_dir" )) =~ "plugins" ]]; then
    echo -e "\nNot in the plugin root directory\n"
    exit 1
fi

echo -e "\ntest && commit -a || restore .\n"

app_dir=$(dirname $(dirname $(dirname $current_dir)))
tmp_file=$app_dir/test_results.temp.txt
phpunit=$app_dir/lib/pkp/lib/vendor/phpunit/phpunit/phpunit
test_config=$app_dir/lib/pkp/tests/phpunit-env2.xml

find . -name tests -type d -exec sh -c "php $phpunit --configuration $test_config -v \"{}\" | tee -a $tmp_file" \; && (grep -q "FAILURES" $tmp_file && git restore . || git commit -a)

rm $tmp_file

echo -e "\nEND OF TCR"
